name: Release Drafter

on:
  push:
    branches: [main]
  # Needed for the autolabeler to label PRs as they're opened/updated.
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: read

jobs:
  update_release_draft:
    permissions:
      contents: write # create/update the draft release
      pull-requests: write # apply autolabels
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v6
        with:
          config-name: release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
